version: '3.1'

services:

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: oneboard
      MYSQL_DATABASE: oneboard
      MYSQL_USER: oneboard
      MYSQL_PASSWORD: oneboard
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 5050:80
    volumes:
      - /sessions
    external_links:
      - mysql:db

  grafana:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_USER = admin
      - GF_SECURITY_ADMIN_PASSWORD = oneboard
    ports:
      - 5000:3000
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
    mysql:
    sessions:
    grafana-storage:
